phraseapp:
  host: http://localhost:3000/api
  file_format: yml
  project_id: abe2ca9e663fbe17acd9fd87b6c0de19
  push:
    sources:
      -
        file: ./<locale_name>.yml
  pull:
    targets:
      -
        file: ./<locale_name>.yml
