phraseapp:
  host: http://localhost:3000/api
  file_format: yml
  project_id: 1f8a5da3da0414afa3eb8e57da454bdd
  push:
    sources:
      -
        file: ./<locale_name>.yml
  pull:
    targets:
      -
        file: ./<locale_name>.yml
